### ISSUE TITLE
Coveralls にもカバレッジがアップロードされていない

### ISSUE THREAD

**Issue by srz-zumix** [srz-zumix/iutest#234]
```
/home/travis/.rvm/gems/ruby-2.5.3/gems/lcoveralls-0.2.3/lib/lcoveralls/runner.rb:97:in `format': incomplete format specifier; use %% (double %) instead (ArgumentError)
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/lcoveralls-0.2.3/lib/lcoveralls/runner.rb:97:in `get_percentage'
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/lcoveralls-0.2.3/lib/lcoveralls/runner.rb:158:in `block (2 levels) in get_source_files'
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/lcoveralls-0.2.3/lib/lcoveralls/runner.rb:122:in `each'
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/lcoveralls-0.2.3/lib/lcoveralls/runner.rb:122:in `block in get_source_files'
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/lcoveralls-0.2.3/lib/lcoveralls/runner.rb:116:in `each'
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/lcoveralls-0.2.3/lib/lcoveralls/runner.rb:116:in `get_source_files'
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/lcoveralls-0.2.3/lib/lcoveralls/runner.rb:265:in `run'
	from /home/travis/.rvm/gems/ruby-2.5.3/gems/lcoveralls-0.2.3/bin/lcoveralls:23:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.5.3/bin/lcoveralls:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.5.3/bin/lcoveralls:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
	from /home/travis/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
GNUmakefile:275: recipe for target 'send-coveralls' failed
```

こっちは年明けてからできてないっぽい

#233

**Comment by srz-zumix** [comment]
あ、これじゃん
https://github.com/pcolby/lcoveralls/pull/8

**Comment by srz-zumix** [comment]
codecov がしたので、こっちは clang にしたい

clang with lcov でエラー

"""
geninfo: ERROR: /home/travis/build/srz-zumix/iutest/test/assertion_return_tests.gcno: reached unexpected end of file
"""

**Comment by srz-zumix** [comment]
http://logan.tw/posts/2015/04/28/check-code-coverage-with-clang-and-lcov/#create-a-wrapper-script-for-lcov
